/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay ()
{
for (int i=0;i<10000;i++)
	;
}

void i2c_init ()
{
	RCC-> AHB1ENR |= (1u<<1) ; //enable
	GPIOB -> MODER  &=~ (1u<<16) ; //8
	GPIOB -> MODER |= (1u<<17) ;

	GPIOB -> MODER &=~ (1u<<18) ;
	GPIOB -> MODER |=  (1u<<19)  ;

	GPIOB-> OTYPER |= (1u<<8) ;
	GPIOB-> OTYPER  |= (1u<<9) ;

	GPIOB ->PUPDR |= (1u << 16);
	GPIOB ->PUPDR  &=(1u <<  17);

	GPIOB ->PUPDR |= (1u << 18);
	GPIOB ->PUPDR &= (1u << 19);

	GPIOB ->AFR[1] &=~ (1U<<0) ;
	GPIOB ->AFR[1] &=~ (1U<<1) ;
	GPIOB ->AFR[1] |=  (1U<<2) ;
	GPIOB ->AFR[1] &=~(1u<<3)  ;

	GPIOB ->AFR[1] &=~ (1U<<4) ;
	GPIOB ->AFR[1] &=~ (1U<<5) ;
	GPIOB ->AFR[1] |=  (1U<<6) ;
	GPIOB ->AFR[1] &=~ (1u<<7) ;

    //rcc enable

	RCC -> APB1ENR |= (1U<<21) ;
	I2C1 ->CR2 (1U<<4) ;
	I2C1 ->CCR =80 ;

	I2C1-> TRISE = 17 ;
	I2C1->CR1 |=(1u<<0) ;

}

void i2c_send_data(uint8_t saddr,int n,uint8_t *data)
{
	I2C1->CR1 |=(1U<<8) ;
	while (!(I2C1->SR1 & (1u<<0))) ;
	sadrr <<= 1 ;
	sadrr &=~(1u<<0) ;
    I2C1->DR =saddr ;

}





int main(void)
{
    /* Loop forever */
	for(;;);

}





